music_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
]

webapp/urls.py
from django.urls import path

from webapp.views import *

urlpatterns = [
    path('', index, name='home'),
    path('about/', about, name='about'),
    path('blog/', blog, name='blog'),
    path('contact/', contact, name='contact'),
    path('events/', events, name='events'),
    path('gallery/', gallery, name='gallery'),
    path('base/', base, name='base'),
]

webapp/models.py
from django.db import models

# Create your models here.

webapp/views.py
from django.shortcuts import render

app_name = 'webapp'

def index(request):
    return render(request, 'webapp/index.html')

def about(request):
    return render(request, 'webapp/about.html')

def blog(request):
    return render(request, 'webapp/blog.html')

def contact(request):
    return render(request, 'webapp/contact.html')

def events(request):
    return render(request, 'webapp/events.html')

def gallery(request):
    return render(request, 'webapp/gallery.html')

def base(request):
    return render(request, 'webapp/base.html')

webapp/templates/webapp/about.html
{% extends 'webapp/base.html' %}
{% load static %}

<body>
{% block content %}
<div class="about">
	<div class="container">
		<h3>About me</h3>
			<div class="ab-top">
				<div class="col-md-6 ab-lft">
					<img src="{% static 'webapp/images/1.jpg' %}" alt=" " class="img-responsive">
				</div>
				<div class="col-md-6 ab-rgt">
					<h4>Slightly believable</h4>
					<p>Lorem Ipsum is simply dummy text of the printing and words which don't look even slightly dummy text of the printing and words which don't look even slightly believable.</p>
					<p> If words which don't look even slightly believable. If  believable. If words which don't look even slightly believable. If you are  are going to use a passage of Lorem Ipsum typesetting industry. Lorem Ipsum has beenLorem Ipsum is simply dummy text of the printing and words which don't look even slightly believable. If words which don't look even slightly believable. If you are  are going to use a passage of Lorem Ipsum typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,  the industry's standard dummy text ever since the 1500s, </p>
				</div>
				<div class="clearfix"></div>
			</div>
			<h3>Biography</h3>
			<div class="ab-btm">
				<div class="ab-l">
					<h6>2010 -</h6>
				</div>
				<div class="ab-r">
					<p>Lorem Ipsum is simply dummy text of the printing and words which don't look even slightly dummy text of the printing and  Lorem Ipsum typesetting industry. Lorem Ipsum has been the  words which don't look even slightly believable.</p>
				</div>
					<div class="clearfix"></div>
			</div>
			<div class="ab-btm">
				<div class="ab-l">
					<h6>2011 -</h6>
				</div>
				<div class="ab-r">
					<p>Lorem Ipsum is simply dummy text of the printing and words which don't look even slightly dummy text of the printing and words which  Lorem Ipsum typesetting industry. Lorem Ipsum has been the  don't look even slightly believable.</p>
				</div>
					<div class="clearfix"></div>
			</div>
			<div class="ab-btm">
				<div class="ab-l">
					<h6>2012 -</h6>
				</div>
				<div class="ab-r">
					<p>Lorem Ipsum is simply dummy text of the printing and words which don't look even slightly dummy text of the  Lorem Ipsum typesetting industry. Lorem Ipsum has been the  printing and words which don't look even slightly believable.</p>
				</div>
					<div class="clearfix"></div>
			</div>
			<div class="ab-btm">
				<div class="ab-l">
					<h6>2013 -</h6>
				</div>
				<div class="ab-r">
					<p>Lorem Ipsum is simply dummy text  Lorem Ipsum typesetting industry. Lorem Ipsum has been the  of the printing and words which don't look even slightly dummy text of the printing and words which don't look even slightly believable.</p>
				</div>
					<div class="clearfix"></div>
			</div>
			<div class="ab-btm">
				<div class="ab-l">
					<h6>2014 -</h6>
				</div>
				<div class="ab-r">
					<p>Lorem Ipsum is simply dummy text of the printing  Lorem Ipsum typesetting industry. Lorem Ipsum has been the  and words which don't look even slightly dummy text of the printing and words which don't look even slightly believable.</p>
				</div>
					<div class="clearfix"></div>
			</div>
			<div class="ab-btm">
				<div class="ab-l">
					<h6>2015 -</h6>
				</div>
				<div class="ab-r">
					<p>Lorem Ipsum is simply dummy text of the printing and words  Lorem Ipsum typesetting industry. Lorem Ipsum has been the  which don't look even slightly dummy text of the printing and words which don't look even slightly believable.</p>
				</div>
					<div class="clearfix"></div>
			</div>
	</div>
</div>
{% endblock %}
</body>

webapp/templates/webapp/base.html
{% load static %}

<!DOCTYPE HTML>
<html>

<head>
<title>TUCHA | Home</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="{% static 'webapp/css/bootstrap.css' %}" rel='stylesheet' type='text/css' />
<!-- Custom Theme files -->
<link href="{% static 'webapp/css/style.css' %}" rel='stylesheet' type='text/css' />
<script src="{% static 'webapp/js/jquery-1.11.1.min.js' %}"></script>
<!--webfonts-->
   <link href='//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,400,300,600,700|Six+Caps' rel='stylesheet' type='text/css'>
<!--//webfonts-->
</head>


<!--banner-->
<div class="banner" id="home">
	<div class="header-top">
		<div class="header-bottom">
			<div class="fixed-header">
				<div class="logo">
					<h1><a href="{% url 'webapp:home' %}">TUCHA<span>music</span></a></h1>
				</div>
			<div class="hd-lt">
			<span class="menu"> </span>
			<div class="top-menu">
			<nav class="cl-effect-21">
				<ul>
					<li><a class="active" href="{% url 'webapp:home' %}">Home</a></li>
					<li><a href="{% url 'webapp:about' %}">About</a></li>
					<li><a href="{% url 'webapp:events' %}">Events</a></li>
					<li><a href="{% url 'webapp:gallery' %}">Gallery</a></li>
					<li><a href="{% url 'webapp:blog' %}">Blog</a></li>
					<li><a href="{% url 'webapp:contact' %}">Contact Us</a></li>
					<div class="clearfix"></div>
				</ul>
			</nav>
			</div>

		<!-- script for menu -->
				<script>
				$( "span.menu" ).click(function() {
				  $( ".top-menu" ).slideToggle( "slow", function() {
				    // Animation complete.
				  });
				});
			</script>
			<!-- script for menu -->
			<script>
		$(document).ready(function() {
			 var navoffeset=$(".header-bottom").offset().top;
			 $(window).scroll(function(){
				var scrollpos=$(window).scrollTop();
				if(scrollpos >=navoffeset){
					$(".header-bottom").addClass("fixed");
				}else{
					$(".header-bottom").removeClass("fixed");
				}
			 });

		});
		</script>
		<div class="header-right">
					<h6>Follows Us :</h6>
						<ul class="f-icons">
							<li><a href="#" class="facebook"> </a></li>
							<li><a href="#" class="p"> </a></li>
							<li><a href="#" class="twitter"> </a></li>
						</ul>
							<div class="clearfix"></div>
				</div>
				<div class="clearfix"></div>
		</div>
		<div class="clearfix"></div>
	 </div>

	 </div>
	 </div>
</div>
<!--banner-->
{% block content %}{% endblock %}
<!-- footer -->
<div class="footer">
	<div class="container">
		<div class="col-md-3 footer-left">
			<h3>More Info</h3>
				<li><a href="#">How to order</a></li>
				<li><a href="#">Faq</a></li>
				<li><a href="#">Locatio</a></li>
				<li><a href="#">Shipping</a></li>
				<li><a href="#">Membership</a></li>
		</div>
		<div class="col-md-3 footer-left">
			<h3>Contact Us</h3>
			<p>Contrary to popular belief</p>
			<p>The standard chunk</p>
			<p>office : +12 34 995 0792</p>
		</div>
		<div class="col-md-3 social">
			<h3>Follow Us</h3>
					<ul>
							<li><a href="#" class="facebook"> </a></li>
							<li><a href="#" class="p"> </a></li>
							<li><a href="#" class="twitter"> </a></li>
							<li><a href="#" class="goog"> </a></li>
						</ul>
		</div>
		<div class="col-md-3 footer-left">
			<h3>Newsletter</h3>
			<form>
				<input type="text" placeholder="Enter email id" required="">
			</form>
			<div class="button">
					<form>
						<input type="submit" value="Subscribe">
					</form>
				</div>
				<div class="clearfix"> </div>
		</div>
		<div class="clearfix"></div>
		<div class="footer-bottom">
			<p>Copyrights © 2023 Tucha Music . All rights reserved | Design by <a href="https://t.me/ultravioletpartyeyes">The creator</a></p>
		</div>
	</div>
</div>
<!-- footer -->

</html>

webapp/templates/webapp/blog.html
{% extends 'webapp/base.html' %}
{% load static %}


<body>
{% block content %}
<div class="pages">
	<div class="container">
				<div class="headdings">
					<h3 class="ghj">Headings</h3>
						<div class="bs-example">
							<table class="table">
							  <tbody>
								<tr>
								  <td><h1 id="h1.-bootstrap-heading">h1. Bootstrap heading<a class="anchorjs-link" href="#h1.-bootstrap-heading"><span class="anchorjs-icon"></span></a></h1></td>
								  <td class="type-info">Semibold 36px</td>
								</tr>
								<tr>
								  <td><h2 id="h2.-bootstrap-heading">h2. Bootstrap heading<a class="anchorjs-link" href="#h2.-bootstrap-heading"><span class="anchorjs-icon"></span></a></h2></td>
								  <td class="type-info">Semibold 30px</td>
								</tr>
								<tr>
								  <td><h3 id="h3.-bootstrap-heading">h3. Bootstrap heading<a class="anchorjs-link" href="#h3.-bootstrap-heading"><span class="anchorjs-icon"></span></a></h3></td>
								  <td class="type-info">Semibold 24px</td>
								</tr>
								<tr>
								  <td><h4 id="h4.-bootstrap-heading">h4. Bootstrap heading<a class="anchorjs-link" href="#h4.-bootstrap-heading"><span class="anchorjs-icon"></span></a></h4></td>
								  <td class="type-info">Semibold 18px</td>
								</tr>
								<tr>
								  <td><h5 id="h5.-bootstrap-heading">h5. Bootstrap heading<a class="anchorjs-link" href="#h5.-bootstrap-heading"><span class="anchorjs-icon"></span></a></h5></td>
								  <td class="type-info">Semibold 14px</td>
								</tr>
								<tr>
								  <td><h6>h6. Bootstrap heading</h6></td>
								  <td class="type-info">Semibold 12px</td>
								</tr>
							  </tbody>
							</table>
						</div>
				</div>
				<div class="Buttons">
					<h3 class="ghj">Buttons</h3>
					  <h1>
						<a href="#"><span class="label label-default">Default</span></a>
						<a href="#"><span class="label label-primary">Primary</span></a>
						<a href="#"><span class="label label-success">Success</span></a>
						<a href="#"><span class="label label-info">Info</span></a>
						<a href="#"><span class="label label-warning">Warning</span></a>
						<a href="#"><span class="label label-danger">Danger</span></a>
					  </h1>
					  <h2>
						<a href="#"><span class="label label-default">Default</span></a>
						<a href="#"><span class="label label-primary">Primary</span></a>
						<a href="#"><span class="label label-success">Success</span></a>
						<a href="#"><span class="label label-info">Info</span></a>
						<a href="#"><span class="label label-warning">Warning</span></a>
						<a href="#"><span class="label label-danger">Danger</span></a>
					  </h2>
					  <h3>
						<a href="#"><span class="label label-default">Default</span></a>
						<a href="#"><span class="label label-primary">Primary</span></a>
						<a href="#"><span class="label label-success">Success</span></a>
						<a href="#"><span class="label label-info">Info</span></a>
						<a href="#"><span class="label label-warning">Warning</span></a>
						<a href="#"><span class="label label-danger">Danger</span></a>
					  </h3>
					  <h4>
						<a href="#"><span class="label label-default">Default</span></a>
						<a href="#"><span class="label label-primary">Primary</span></a>
						<a href="#"><span class="label label-success">Success</span></a>
						<a href="#"><span class="label label-info">Info</span></a>
						<a href="#"><span class="label label-warning">Warning</span></a>
						<a href="#"><span class="label label-danger">Danger</span></a>
					  </h4>
					  <h5>
						<a href="#"><span class="label label-default">Default</span></a>
						<a href="#"><span class="label label-primary">Primary</span></a>
						<a href="#"><span class="label label-success">Success</span></a>
						<a href="#"><span class="label label-info">Info</span></a>
						<a href="#"><span class="label label-warning">Warning</span></a>
						<a href="#"><span class="label label-danger">Danger</span></a>
					  </h5>
					  <h6>
						<a href="#"><span class="label label-default">Default</span></a>
						<a href="#"><span class="label label-primary">Primary</span></a>
						<a href="#"><span class="label label-success">Success</span></a>
						<a href="#"><span class="label label-info">Info</span></a>
						<a href="#"><span class="label label-warning">Warning</span></a>
						<a href="#"><span class="label label-danger">Danger</span></a>
					  </h6>
				</div>
				<div class="progress-bars">
				 <h3 class="ghj">Progress Bars</h3>
					 <div class="tab-content">
						  <div class="tab-pane active" id="domprogress">
							  <div class="progress">    
								<div class="progress-bar progress-bar-primary" style="width: 20%"></div>
							  </div>
							  <p>Info with <code>progress-bar-info</code> class.</p>
							  <div class="progress">    
								<div class="progress-bar progress-bar-info" style="width: 60%"></div>
							  </div>
							  <p>Success with <code>progress-bar-success</code> class.</p>
							  <div class="progress">
								<div class="progress-bar progress-bar-success" style="width: 30%"></div>
							  </div>
							  <p>Warning with <code>progress-bar-warning</code> class.</p>
							  <div class="progress">
								<div class="progress-bar progress-bar-warning" style="width: 70%"></div>
							  </div>
							  <p>Danger with <code>progress-bar-danger</code> class.</p>
							  <div class="progress">
								<div class="progress-bar progress-bar-danger" style="width: 50%"></div>
							  </div>
							  <p>Inverse with <code>progress-bar-inverse</code> class.</p>
							  <div class="progress">
								<div class="progress-bar progress-bar-inverse" style="width: 40%"></div>
							  </div>
							   <p>Inverse with <code>progress-bar-inverse</code> class.</p>
							  <div class="progress">
								<div class="progress-bar progress-bar-success" style="width: 35%"><span class="sr-only">35% Complete (success)</span></div>
								<div class="progress-bar progress-bar-warning" style="width: 20%"><span class="sr-only">20% Complete (warning)</span></div>
								<div class="progress-bar progress-bar-danger" style="width: 10%"><span class="sr-only">10% Complete (danger)</span></div>
							  </div>
						</div>
				   </div>
				</div>
				<div class="alerts">
				  <h3 class="ghj">Alerts</h3>
				   <div class="alert alert-success" role="alert">
					<strong>Well done!</strong> You successfully read this important alert message.
				   </div>
				   <div class="alert alert-info" role="alert">
					<strong>Heads up!</strong> This alert needs your attention, but it's not super important.
				   </div>
				   <div class="alert alert-warning" role="alert">
					<strong>Warning!</strong> Best check yo self, you're not looking too good.
				   </div>
				   <div class="alert alert-danger" role="alert">
					<strong>Oh snap!</strong> Change a few things up and try submitting again.
				   </div>
				</div>
				<div class="pagenatin">
					<h3 class="ghj">Pagination</h3>
						<div class="col-md-6">
						  <nav>
						  <ul class="pagination pagination-lg">
							<li><a href="#" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
							<li><a href="#">1</a></li>
							<li><a href="#">2</a></li>
							<li><a href="#">3</a></li>
							<li><a href="#">4</a></li>
							<li><a href="#">5</a></li>
							<li><a href="#" aria-label="Next"><span aria-hidden="true">»</span></a></li>
						  </ul>
						  </nav>
						  <nav>
						  <ul class="pagination">
							<li><a href="#" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
							<li><a href="#">1</a></li>
							<li><a href="#">2</a></li>
							<li><a href="#">3</a></li>
							<li><a href="#">4</a></li>
							<li><a href="#">5</a></li>
							<li><a href="#" aria-label="Next"><span aria-hidden="true">»</span></a></li>
						  </ul>
						  </nav>
						  <nav>
							<ul class="pagination pagination-sm">
								<li><a href="#" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
								<li><a href="#">1</a></li>
								<li><a href="#">2</a></li>
								<li><a href="#">3</a></li>
								<li><a href="#">4</a></li>
								<li><a href="#">5</a></li>
								<li><a href="#" aria-label="Next"><span aria-hidden="true">»</span></a></li>
							</ul>
						  </nav>
						</div>
						<div class="col-md-6">
							<nav>
								<ul class="pagination pagination-lg">
										<li class="disabled"><a href="#"><i class="fa fa-angle-left">«</i></a></li>
										<li class="active"><a href="#">1</a></li>
										<li><a href="#">2</a></li>
										<li><a href="#">3</a></li>
										<li><a href="#">4</a></li>
										<li><a href="#">5</a></li>
										<li><a href="#"><i class="fa fa-angle-right">»</i></a></li>
								</ul>
							</nav>
							<nav>
							  <ul class="pagination">
								<li class="disabled"><a href="#" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
								<li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li>
								<li><a href="#">2</a></li>
								<li><a href="#">3</a></li>
								<li><a href="#">4</a></li>
								<li><a href="#">5</a></li>
								<li><a href="#" aria-label="Next"><span aria-hidden="true">»</span></a></li>
							 </ul>
							</nav>
							<nav>
								 <ul class="pagination pagination-sm">
									<li class="disabled"><a href="#"><i class="fa fa-angle-left"></i>«</a></li>
									<li class="active"><a href="#">1</a></li>
									<li><a href="#">2</a></li>
									<li><a href="#">3</a></li>
									<li><a href="#">4</a></li>
									<li><a href="#">5</a></li>
									<li><a href="#"><i class="fa fa-angle-right"></i>»</a></li>
								</ul>
							</nav>
						</div>
						<div class="clearfix"> </div>
				</div>
				<div class="bread-crumbs">
					 <h3 class="ghj">Breadcrumbs</h3>
					   <ol class="breadcrumb">
					  <li class="active">Home</li>
					</ol>
					<ol class="breadcrumb">
					  <li><a href="#">Home</a></li>
					  <li class="active">Library</li>
					</ol>
					<ol class="breadcrumb">
					  <li><a href="#">Home</a></li>
					  <li><a href="#">Library</a></li>
					  <li class="active">Data</li>
					</ol>
				</div>
				<div class="appearance">
				 <h3 class="ghj">Badges</h3>
					<div class="col-md-6">
						<p>Add modifier classes to change the appearance of a badge.</p>
						  <table class="table table-bordered">
							<thead>
								<tr>
									<th width="50%">Classes</th>
									<th width="50%">Badges</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>No modifiers</td>
									<td><span class="badge">42</span></td>
								</tr>
								<tr>
									<td><code>.badge-primary</code></td>
									<td><span class="badge badge-primary">1</span></td>
								</tr>
								<tr>
									<td><code>.badge-success</code></td>
									<td><span class="badge badge-success">22</span></td>
								</tr>
								<tr>
									<td><code>.badge-info</code></td>
									<td><span class="badge badge-info">30</span></td>
								</tr>
								<tr>
									<td><code>.badge-warning</code></td>
									<td><span class="badge badge-warning">412</span></td>
								</tr>
								<tr>
									<td><code>.badge-danger</code></td>
									<td><span class="badge badge-danger">999</span></td>
								</tr>
							</tbody>
						  </table>                    
					</div>
					<div class="col-md-6">
					  <p>Easily highlight new or unread items with the <code>.badge</code> class</p>
						<div class="list-group list-group-alternate"> 
							<a href="#" class="list-group-item"><span class="badge">201</span> <i class="ti ti-email"></i> Inbox </a> 
							<a href="#" class="list-group-item"><span class="badge badge-primary">5021</span> <i class="ti ti-eye"></i> Profile visits </a> 
							<a href="#" class="list-group-item"><span class="badge">14</span> <i class="ti ti-headphone-alt"></i> Call </a> 
							<a href="#" class="list-group-item"><span class="badge">20</span> <i class="ti ti-comments"></i> Messages </a> 
							<a href="#" class="list-group-item"><span class="badge badge-warning">14</span> <i class="ti ti-bookmark"></i> Bookmarks </a> 
							<a href="#" class="list-group-item"><span class="badge badge-danger">30</span> <i class="ti ti-bell"></i> Notifications </a> 
						</div>
					</div>
				   <div class="clearfix"> </div>
				</div>
				<div class="distracted">
				  <h3 class="ghj">Wells</h3>
					   <div class="well">
						There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration
					   </div>
					   <div class="well">
						It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here
					   </div>
					   <div class="well">
						Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic
					   </div>
				</div>
			</div>
	</div>
{% endblock %}
</body>

webapp/templates/webapp/contact.html
{% extends 'webapp/base.html' %}
{% load static %}

<body>
{% block content %}
<div class="contact">
		<div class="container">
			<div class="contact-top heading">
				<h3>CONTACT US</h3>
			</div>
			<div class="contact-bottom">
				<input type="text" value="Name" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Name';}">
				<input type="text" value="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}">
				<input type="text" value="Phone" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Phone';}">
				<textarea value="Message:" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Message';}">Message..</textarea>
				<div class="submit-btn">
					<form>
						<input type="submit" value="SUBMIT">
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="map">
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2884.310671366718!2d7.283884900000001!3d43.70409239999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12cddab7066db4e1%3A0x7e52715fee03b279!2sNICE+FRANCE!5e0!3m2!1sen!2sin!4v1435662218413" frameborder="0" style="border:0" allowfullscreen=""></iframe>	
	</div>
{% endblock %}
</body>

webapp/templates/webapp/events.html
{% extends 'webapp/base.html' %}
{% load static %}


<body>
{% block content %}

<div class="events">
	<div class="container">
		<div class="col-md-9 events-left">
			<h3>Featured events</h3>
			<div class="eve-top">
				<div class="col-md-5 eve-lt">
					<div class="ev-lft">
						<img src="{% static 'webapp/images/img4.jpg' %}" alt=" " class="img-responsive">
					</div>
					<div class="ev-rgt">
						<h5>29</h5>
						<h6>August</h6>
					</div>	
					<div class="clearfix"></div>
				</div>
				<div class="col-md-7 eve-rt">
					<h4>Variations of passages</h4>
					<p>There are many variations of passages Slightly believable of Lorem Ipsum available, but the majority have suffered alteration</p>
				</div>
				<div class="clearfix"></div>
			</div>
			<div class="eve-top">
				<div class="col-md-5 eve-lt">
					<div class="ev-lft">
						<img src="{% static 'webapp/images/img5.jpg' %}" alt=" " class="img-responsive">
					</div>
					<div class="ev-rgt">
						<h5>10</h5>
						<h6>September</h6>
					</div>	
					<div class="clearfix"></div>
				</div>
				<div class="col-md-7 eve-rt">
					<h4>Ipsum available</h4>
					<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration</p>
				</div>
				<div class="clearfix"></div>
			</div>
			<div class="eve-top">
				<div class="col-md-5 eve-lt">
					<div class="ev-lft">
						<img src="{% static 'webapp/images/img3.jpg' %}" alt=" " class="img-responsive">
					</div>
					<div class="ev-rgt">
						<h5>22</h5>
						<h6>October</h6>
					</div>	
					<div class="clearfix"></div>
				</div>
				<div class="col-md-7 eve-rt">
					<h4>Passages of Lorem</h4>
					<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration</p>
				</div>
				<div class="clearfix"></div>
			</div>
			<div class="eve-top">
				<div class="col-md-5 eve-lt">
					<div class="ev-lft">
						<img src="{% static 'webapp/images/img2.jpg' %}" alt=" " class="img-responsive">
					</div>
					<div class="ev-rgt">
						<h5>12</h5>
						<h6>November</h6>
					</div>	
					<div class="clearfix"></div>
				</div>
				<div class="col-md-7 eve-rt">
					<h4>The majority have</h4>
					<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration</p>
				</div>
				<div class="clearfix"></div>
			</div>
			<div class="eve-top">
				<div class="col-md-5 eve-lt">
					<div class="ev-lft">
						<img src="{% static 'webapp/images/img1.jpg' %}" alt=" " class="img-responsive">
					</div>
					<div class="ev-rgt">
						<h5>23</h5>
						<h6>December</h6>
					</div>	
					<div class="clearfix"></div>
				</div>
				<div class="col-md-7 eve-rt">
					<h4>Suffered alteration</h4>
					<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration</p>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
		<div class="col-md-3 events-right">
			<h3>Archive</h3>
			<div class="eve-btm">
				<li><a href="#">January 2015</a></li>
				<li><a href="#">February 2015</a></li>
				<li><a href="#">March 2015</a></li>
				<li><a href="#">April 2015</a></li>
				<li><a href="#">May 2015</a></li>
				<li><a href="#">June 2015</a></li>
				<li><a href="#">July 2015</a></li>
				<li><a href="#">August 2015</a></li>
				<li><a href="#">September 2015</a></li>
				<li><a href="#">October 2015</a></li>
				<li><a href="#">November 2015</a></li>
				<li><a href="#">December 2015</a></li>
			</div>
		</div>
			<div class="clearfix"></div>
	</div>
</div>
{% endblock %}
</body>